import React from 'react'
import { Audio, Sequence, interpolate, staticFile } from 'remotion'
import {
  ARRIVALS,
  AWARDS,
  CARD_LAND,
  CARD_LIFT,
  CARD_SHED,
  MONEY_FILL,
  MONEY_PULL,
  MONEY_PUSH,
  DIAL_STEPS,
  HITS,
  NUDGE_LAND,
  NUDGE_SEND,
  PUSHES,
  REACTIONS,
  SECTION,
  STREAK,
  THEIRS_CLOSE,
  WAVE_RINGS,
  WAVE_START,
  WAVE_STEP,
  weekBeat,
} from './cues'
import { FPS, filmFrames, framesPerBeat, hasSilence, type Track } from './tracks'
import type { Take } from './voice'

/**
 * Sound: the music, and the film's own effects on top.
 *
 * The effects are placed here, on the picture's cues, rather than mixed into the score — so
 * every whoosh and click stays on its moment whichever track is underneath. The one-shots
 * are generated by `scripts/score.mjs` into `public/next-week/sfx/`.
 *
 * The voiceover, when there is one, is laid the same way: each line of the one take on its
 * beat (`voice.ts`), with the music ducked under it.
 */

type Hit = { at: number; sfx: string; volume: number; onlySpliced?: boolean }

const REEL = [62.5, 64, 65.5, 67, 68.5, 70.3, 73.3]
const YEAR_TICKS = [2, 3, 4, 5, 6, 7, 8, 9, 10, 46, 47, 48, 49, 50, 51, 52]

export const HITS_LIST: Hit[] = [
  ...PUSHES.map(([start], i) => ({ at: start, sfx: 'whoosh', volume: 0.35 + i * 0.08 })),
  { at: STREAK[0], sfx: 'streak', volume: 0.8 },
  { at: SECTION.stop, sfx: 'stop', volume: 0.9 },
  ...ARRIVALS.map((at, i) => ({ at, sfx: `arrive${i + 1}`, volume: 0.55 })),
  { at: 30, sfx: 'riser', volume: 0.22, onlySpliced: true },
  { at: SECTION.through, sfx: 'fly', volume: 0.6 },
  { at: DIAL_STEPS[0]!, sfx: 'grab', volume: 0.5 },
  ...DIAL_STEPS.slice(1).map((at) => ({ at: at - 0.05, sfx: 'click', volume: 0.6 })),
  { at: 57.8, sfx: 'drop', volume: 0.5 },
  ...REEL.map((at) => ({ at, sfx: 'tick', volume: 0.32 })),
  { at: SECTION.buy, sfx: 'press', volume: 0.6 },
  { at: 78, sfx: 'bend', volume: 0.55 },
  // The cup and the sparkle used to start on the same frame on the music's downbeat, the loudest
  // instant in the film. The sparkle now follows by a tenth of a beat and the cup is softer; the
  // limiter in scripts/render.mjs catches what is left (it measured +0.38 dBFS without it).
  { at: SECTION.kept, sfx: 'cup', volume: 0.7 },
  { at: SECTION.kept + 0.12, sfx: 'sparkle', volume: 0.45 },
  { at: CARD_LIFT, sfx: 'swoosh', volume: 0.4 },
  { at: CARD_SHED, sfx: 'shed', volume: 0.45 },
  { at: 94, sfx: 'swoosh', volume: 0.4 },
  { at: CARD_LAND, sfx: 'ding', volume: 0.6 },
  ...REACTIONS.map((at) => ({ at, sfx: 'pop', volume: 0.5 })),
  { at: NUDGE_SEND, sfx: 'swoosh', volume: 0.45 },
  { at: NUDGE_LAND, sfx: 'ding', volume: 0.6 },
  { at: THEIRS_CLOSE, sfx: 'cup', volume: 0.75 },
  ...Array.from({ length: WAVE_RINGS }, (_, i) => ({
    at: WAVE_START + i * WAVE_STEP,
    sfx: 'tick',
    volume: 0.3 + i * 0.03,
  })),
  { at: 118, sfx: 'fly', volume: 0.45 },
  ...YEAR_TICKS.map((w) => ({ at: weekBeat(w - 0.08), sfx: 'tick', volume: 0.3 })),
  { at: weekBeat(7.7), sfx: 'streak', volume: 0.35 },
  ...AWARDS.map((a) => ({
    at: a.week === 1 ? SECTION.year + 0.4 : weekBeat(a.week - 0.25),
    sfx: 'sparkle',
    volume: 0.35,
  })),
  // The money: out to ten years, the rows filling, the sum landing, back in to the last week.
  { at: MONEY_PULL[0], sfx: 'fly', volume: 0.45 },
  { at: MONEY_FILL[0], sfx: 'streak', volume: 0.3 },
  { at: MONEY_FILL[1] - 0.2, sfx: 'sparkle', volume: 0.45 },
  { at: MONEY_PUSH[0], sfx: 'fly', volume: 0.5 },
  ...HITS.map((at) => ({ at, sfx: 'hit', volume: 0.85 })),
  { at: SECTION.logo, sfx: 'cup', volume: 0.7 },
]

const ramp = (f: number, from: [number, number], to: [number, number]) =>
  interpolate(f, from, to, { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })

/**
 * The whole mix, one fader: −1 dB. The hard stop and the three closing hits peaked just
 * over 0 dBFS on the chosen track; this keeps them under it without touching the balance.
 * The kept moment still crossed 0 dBFS at any fader setting, so the finished file goes through
 * a −1 dBFS limiter (scripts/render.mjs).
 */
const MASTER = 0.89

/** How far the music comes down under the voice (about −9 dB), and how fast. */
const DUCK = 0.35
const DUCK_ATTACK = 4
const DUCK_RELEASE = 14

/** The music's level at a frame of the film: 1, or down to `DUCK` while a line is being said. */
function ducking(take: Take | null, fpb: number) {
  const spans = (take?.lines ?? []).map((line) => {
    const start = line.at * fpb
    return [start, start + line.speech * FPS] as const
  })
  return (frame: number) => {
    let under = 0
    for (const [start, end] of spans) {
      const inside = Math.min(
        ramp(frame, [start - DUCK_ATTACK, start], [0, 1]),
        ramp(frame, [end, end + DUCK_RELEASE], [1, 0]),
      )
      under = Math.max(under, inside)
    }
    return 1 - (1 - DUCK) * under
  }
}

function Voice({ take, fpb }: { take: Take; fpb: number }) {
  return (
    <>
      {take.lines.map((line) => (
        <Sequence
          key={line.src}
          from={Math.max(0, Math.round(line.at * fpb - line.lead * FPS))}
          durationInFrames={Math.ceil(line.seconds * FPS) + 1}
        >
          <Audio src={staticFile(line.src)} volume={MASTER} />
        </Sequence>
      ))}
    </>
  )
}

function Music({ track, duck }: { track: Track; duck: (frame: number) => number }) {
  const total = filmFrames(track.bpm)
  const fpb = framesPerBeat(track.bpm)
  const gain = track.gain ?? 1
  return (
    <>
      {track.edits.map((edit, i) => {
        if (edit.from === null) return null
        const start = Math.round(edit.beat * fpb)
        const next = track.edits[i + 1]
        const length = (next ? Math.round(next.beat * fpb) : total) - start
        // Every edit is a hard cut, with a couple of frames either side so it does not click.
        // The last one fades out over the tail instead of cutting.
        const level = (f: number) =>
          (i === 0 ? 1 : ramp(f, [0, 2], [0, 1])) *
          (next
            ? ramp(f, [length - 3, length], [1, 0])
            : ramp(f, [length - FPS * 2.5, length], [1, 0]))
        return (
          <Sequence key={i} from={start} durationInFrames={length}>
            <Audio
              src={staticFile(track.src)}
              trimBefore={Math.round(edit.from * FPS)}
              volume={(f) => MASTER * gain * level(f) * duck(start + f)}
            />
          </Sequence>
        )
      })}
    </>
  )
}

export function Sound({ track, take }: { track: Track; take: Take | null }) {
  const fpb = framesPerBeat(track.bpm)
  const spliced = hasSilence(track)
  return (
    <>
      <Music track={track} duck={ducking(take, fpb)} />
      {take && <Voice take={take} fpb={fpb} />}
      {HITS_LIST.filter((h) => spliced || !h.onlySpliced).map((h, i) => (
        <Sequence key={i} from={Math.max(0, Math.round(h.at * fpb))} durationInFrames={FPS * 4}>
          <Audio src={staticFile(`next-week/sfx/${h.sfx}.wav`)} volume={MASTER * h.volume} />
        </Sequence>
      ))}
    </>
  )
}
